// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPnm7sE4JrShAFRZVejC4LXmQ1mQj0WrI',
    appId: '1:446631480028:web:42234117f926369bac8219',
    messagingSenderId: '446631480028',
    projectId: 'bookapp-ab099',
    authDomain: 'bookapp-ab099.firebaseapp.com',
    storageBucket: 'bookapp-ab099.appspot.com',
    measurementId: 'G-D1ST1PZ4FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP8xZ7HgvOgIpwYpVng-cCYR6fwL9oPIA',
    appId: '1:446631480028:android:5cf092c1254f472aac8219',
    messagingSenderId: '446631480028',
    projectId: 'bookapp-ab099',
    storageBucket: 'bookapp-ab099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWJcBFBh4V6QcNXcbj7TlmiQZTBKzeybg',
    appId: '1:446631480028:ios:c835cc5436c5228cac8219',
    messagingSenderId: '446631480028',
    projectId: 'bookapp-ab099',
    storageBucket: 'bookapp-ab099.appspot.com',
    iosBundleId: 'com.example.bookapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWJcBFBh4V6QcNXcbj7TlmiQZTBKzeybg',
    appId: '1:446631480028:ios:56092796a3888105ac8219',
    messagingSenderId: '446631480028',
    projectId: 'bookapp-ab099',
    storageBucket: 'bookapp-ab099.appspot.com',
    iosBundleId: 'com.example.bookapplication.RunnerTests',
  );
}
